spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: passenger-service
          uri: http://localhost:9099
          predicates:
            - Path=/passengerinfo/**
        - id: flight-service
          uri: http://localhost:9098
          predicates:
            - Path=/flights/**
        - id: airline
          uri: http://localhost:9097
          predicates:
            - Path=/airline/**
server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/